{% set name = "susi" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/susi-{{ version }}.zip
  sha256: b25a1df7461c26b174de2de274fdc678705a8b8de6df0a7b4d8ed3332904886f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - joblib >=0.13.0
    - numpy >=1.18.5
    - python >=3.7
    - scikit-learn >=0.21.1
    - scipy >=1.3.1
    - tqdm >=4.45.0
    - matplotlib-base >=3.3.0
    - seaborn >=0.11.0
    - pandas >=1.1.5

test:
  imports:
    - susi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/felixriese/susi
  summary: Python package for unsupervised, supervised and semi-supervised self-organizing maps (SOM)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - felixriese
